version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - /mnt/c/Users/forma/Work_BBRMI/seq_pipeline_sandbox/exports:/exports
    ports:
      - 8080:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgesql/data
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_dev

volumes:
  postgres_data:

